# Generated by Django 6.0.2 on 2026-02-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_remove_interest_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='person',
            new_name='ledger_pers_user_id_74ec2b_idx',
            old_name='ledger_pers_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='ledger_tran_user_id_057dfe_idx',
            old_name='ledger_tran_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='ledger_tran_due_dat_3c20b0_idx',
            old_name='ledger_tran_due_dat_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='ledger_tran_date_ffdfdc_idx',
            old_name='ledger_tran_date_idx',
        ),
    ]
